config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'homes#index'
  get 'privacy_policy', to: 'homes#privacy_policy'

  resources :books, only: %i[index show]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/address.rb
class Address < ApplicationRecord
  enum address_type: { billing: 0, shipping: 1 }

  belongs_to :addressable, polymorphic: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :email, :password, :encrypted_password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books, dependent: :destroy
  has_many :books, through: :author_books, dependent: :destroy
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  BOOKS_PER_PAGE = 12
  include ImageUploader::Attachment(:image)

  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :book_images, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :category
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :order
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  enum status: { pending: 0, address: 1, delivery: 2, payment: 3, confirm: 4, complete: 5,
                 in_delivery: 6, delivered: 7, canceled: 8 }

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true
  has_one :coupon, dependent: :nullify
  has_one :credit_card, dependent: :destroy
  has_many :order_items, dependent: :destroy

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :address
    state :delivery
    state :payment
    state :confirm
    state :complete
    state :in_delivery
    state :delivered
    state :canceled

    event :to_address do
      transitions from: :pending, to: :address
    end

    event :fill_delivery do
      transitions from: :address, to: :delivery
    end

    event :payment do
      transitions from: :delivery, to: :payment
    end

    event :confirmation do
      transitions from: :payment, to: :confirm
    end

    event :complete do
      transitions from: :confirm, to: :complete
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  INVALID_QUANTITY = 0

  belongs_to :order
  belongs_to :book

  validates :quantity, numericality: { greater_than: INVALID_QUANTITY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum status: { unprocessed: 0, approved: 1, rejected: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  PASSWORD_FORMAT = /\A(?!.*\s)(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/x

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 facebook]

  validates :email, :password, :encrypted_password, presence: true
  validates :password, format: { with: PASSWORD_FORMAT }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @collection = SortedBooksQuery.new(category_id: book_params[:category_id], sort_by: book_params[:sort_by]).call
    @presenter = BooksPresenter.new(book_params[:current_books_count])
    @books = @collection.limit(@presenter.calculate_limit).decorate
  end

  def show
    if book.present?
      @book = book.decorate
      @reviews = @book.reviews.includes(:user).approved.decorate
    else
      record_not_found
    end
  end

  private

  def book
    Book.includes(:authors).find_by(id: book_params[:id])
  end

  def book_params
    params.permit(:id, :category_id, :sort_by, :current_books_count)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_order&.decorate
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @newest_books = BookDecorator.decorate_collection(
      Book.includes(:authors).last(BookDecorator::NEWEST_BOOKS_COUNT)
    )
  end

  def privacy_policy; end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = SortedOrdersQuery.new(relation: current_user.orders, sort_by: orders_params[:sort_by]).call.decorate
    @orders_presenter = OrdersPresenter.new
  end

  def show
    @order = Order.includes(order_items: [:book]).find(params[:id]).decorate
  end

  private

  def orders_params
    params.permit(:sort_by)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def username
    @username ||= current_user.email.split(/@/).first
  end

  def sign_up?
    controller_name != 'sessions'
  end

  def log_in?
    devise_mapping.registerable? && controller_name != 'registrations'
  end

  def confirmation_instructions?
    devise_mapping.confirmable? && controller_name != 'confirmations'
  end
end

app/views/books/partials/mobile/_sorting.html.haml
.dropdowns.mb-25.visible-xs
  %p.lead.small.mb-10
    = t('.filter_by_category')
  .dropdown
    %a.dropdown-toggle.lead.small{ href: '#', 'data-toggle': 'dropdown', role: 'button',
                                       'aria-haspopup': 'true', 'aria-expanded': 'false' }
      = t('.categories')
      %i.fa.fa-angle-down.dropdown-icon.pull-right
    %ul.dropdown-menu
      - categories.each do |category|
        = link_to category.name, books_path(category_id: category.id)
  %p.lead.small.mb-10
    = t('.filters')
  .dropdown
    %a.dropdown-toggle.lead.small{ href: '#', 'data-toggle': 'dropdown', role: 'button',
                                       'aria-haspopup': 'true', 'aria-expanded': 'false' }
      = t('.sort_by')
      %i.fa.fa-angle-down.dropdown-icon.pull-right
    %ul.dropdown-menu
      - t('books.partials.sorting.catalog_by').map do |key, value|
        %li
          = link_to value, books_path(category_id: params[:category_id], sort_by: key)

app/views/carts/partials/mobile/_orders.html.haml
- order_items.includes([:book]).each do |item|
  .general-cart-item.divider-lg-bottom.mb-30
    %button.close.general-cart-close{ type: 'button', 'aria-label': 'Close' }
      = link_to order_item_path(item.id), method: :delete, class: 'close general-order-close', 'aria-label': 'Close' do
        %span{ 'aria-hidden': 'true' } &times;
    .general-img-wrap-table
      = link_to book_path(item.book) do
        = image_tag(item.book.image_url(:small), class: 'cart-img-shadow')
    = link_to item.book.title, book_path(item.book), class: 'title'
    %table.table
      %tr
        %td
          %span.in-grey-600
            = t('.price')
        %td
          %span.font-16.in-gold-500
            = number_to_currency(item.book.price)
      %tr
        %td.vertical-middle
          %span.in-grey-600
            = t('.quantity')
        %td
          .input-group.quantity-controller
            = link_to order_items_path(order_item: { quantity: -1, book_id: item.book.id }),
                                          method: :post, id: 'minus', class: 'input-link' do
              %i.fa.fa-minus.line-heaght-40
            %input.form-control.quantity-input{ type: 'text', value: item.quantity }
            = link_to order_items_path(order_item: { quantity: 1, book_id: item.book.id }),
                                          method: :post, id: 'plus', class: 'input-link' do
              %i.fa.fa-plus.line-heaght-40
      %tr
        %td
          %span.in-grey-600
            = t('.sub_total')
        %td
          %span.font-16.in-gold-500
            = number_to_currency(item.subtotal_order_items_price)

app/views/checkouts/partials/confirm/mobile/_items.html.haml
- order.order_items.each do |item|
  .general-cart-item.divider-lg.mb-55
    .general-img-wrap-table
      = image_tag(item.book.image_url(:small), class: 'cart-img-shadow')
    %p.title
      = item.book.title
    %p.in-grey-600.fw-300
      = item.book.short_description
    %table.table
      %tr
        %td
          %span.in-grey-600
            = t('.price')
        %td
          %span.font-16.in-gold-500
            = number_to_currency(item.book.price)
      %tr
        %td.vertical-middle
          %span.in-grey-600
            = t('.quantity')
        %td
          %span
            = item.quantity
      %tr
        %td
          %span.in-grey-600
            = t('.total')
        %td
          %span.font-16.in-gold-500
            = number_to_currency(item.subtotal_order_items_price)

app/views/checkouts/partials/payment/_inputs.html.haml
= form.input_field field, class: 'form-control', type: type
- if presenter.field_has_errors?(field)
  %span.help-block
    = presenter.errors.full_messages_for(field).to_sentence

app/views/layouts/partials/_flash.html.haml
- flash.each do |key, value|
  .alert{ class: "flash-#{key}" }
    = value
    %span.close-flash
      %i.fas.fa-times

app/views/layouts/partials/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to t('.home'), root_path, class: 'nav-link home_link'
          %li
            = link_to t('.shop'), books_path, class: 'nav-link shop_link'
          - if user_signed_in?
            %li
              %a.nav-link.orders_link{ href: '#' }
                = t('.orders')
            %li
              %a.nav-link.settings_link{ href: '#' }
                = t('.settings')
          %li
            = link_to t('.privacy_policy'), privacy_policy_path, class: 'nav-link privacy_policy_link'
      .col-sm-3
        %p.general-nav-mail
          = t('.email')
        %p.general-nav-number
          = t('.phone')
        %ul.list-inline.general-align
          %li
            %a.facebook-link.nav-link{ href: '#' }
              %i.fab.fa-facebook-f{ 'aria-hidden': 'true' }
          %li
            %a.twitter-link.nav-link{ href: '#' }
              %i.fab.fa-twitter{ 'aria-hidden': 'true' }
          %li
            %a.google-link.nav-link{ href: '#' }
              %i.fab.fa-google-plus-g{ 'aria-hidden': 'true' }
          %li
            %a.instagram-link.nav-link{ href: '#' }
              %i.fab.fa-instagram{ 'aria-hidden': 'true' }

app/views/layouts/partials/_head.html.haml
%head
  %meta{ charset: 'UTF-8' }/
  %meta{ name: 'viewport', content: 'width=device-width' }/
  %meta{ description: 'Online book shop' }/
  %meta{ keywords: 'book, shop, rg, amazing, turvitan' }/
  %meta{ author: 'Vitalii Turzhanskyi' }/
  %title
    = t('.title')

  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/partials/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{ type: 'button', 'data-toggle': 'collapse', 'data-target': '#navbar' }
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand
        = t('.brand')
      %a.shop-link.pull-right.visible-xs{ href: '#' }
        %span.shop-icon
          %span.shop-quantity 3
    %a.shop-link.pull-right.hidden-xs{ href: '#' }
      %span.shop-icon
        %span.shop-quantity 3
    .navbar-collapse.collapse.pl-30#navbar{ 'aria-expanded': 'false' }
      .visible-xs
        = render partial: 'layouts/partials/mobile/navigation', locals: { categories: categories }
      .hidden-xs
        = render partial: 'layouts/partials/navigation', locals: { categories: categories }

app/views/layouts/partials/_navigation.html.haml
%ul.nav.navbar-nav
  %li
    = link_to t('.home'), root_path, class: 'home_link'
  %li.dropdown
    %a.shop_link.dropdown-toggle{ href: '#', 'data-toggle': 'dropdown', role: 'button',
                                      'aria-haspopup': 'true', 'aria-expanded': 'false' }
      = t('.shop')
    %ul.dropdown-menu
      - categories.each do |category|
        %li
          = link_to category.name, books_path(category_id: category.id)
  - if current_user
    %li
      %a.my_account_link.dropdown-toggle{ href: '#', 'data-toggle': 'dropdown', role: 'button',
                                              'aria-haspopup': 'true', 'aria-expanded': 'false' }
        .fa.fa-user
        %b
          = username
      %ul.dropdown-menu
        %li
          %a{ href: '#' }
            .fas.fa-shopping-cart
            = t('.link.orders')
        %li
          %a{ href: '#' }
            .fa.fa-cog
            = t('.link.settings')
        %li.divider{ role: 'separator' }
        %li
          = link_to destroy_user_session_path, method: :delete, class: 'log_out_link' do
            .fa.fa-sign-out-alt
            = t('.link.log_out')
  - else
    %li
      = link_to new_user_session_path, class: 'log_in_link' do
        .fas.fa-sign-in-alt
        = t('.link.log_in')
    %li
      = link_to new_user_registration_path, class: 'sign_up_link' do
        .fas.fa-user-plus
        = t('.link.sign_up')

app/views/orders/partials/mobile/_items.html.haml
- order.order_items.each do |item|
  .general-cart-item.divider-lg
    .general-img-wrap-table
      = image_tag(item.book.image_url(:small), class: 'cart-img-shadow')
    %p.title
      = item.book.title
    %p.in-grey-600.fw-300
      = item.book.short_description
    %table.table
      %tr
        %td
          %span.in-grey-600
            = t('.price')
        %td
          %span.font-16.in-gold-500
            = number_to_currency(item.book.price)
      %tr
        %td.vertical-middle
          %span.in-grey-600
            = t('.quantity')
        %td
          %span
            = item.quantity
      %tr
        %td
          %span.in-grey-600
            = t('.sub_total')
        %td
          %span.font-16.in-gold-500
            = number_to_currency(item.subtotal_order_items_price)

app/views/orders/partials/mobile/_orders_list.html.haml
- orders.each do |order|
  .general-cart-item.divider-lg-bottom.pt-0
    %table.table
      %tr
        %td.col-half
          %span.in-grey-600
            = t('.number')
        %td.col-half
          %span.general-order-number
            = link_to order.number, order_path(order)
      %tr
        %td
          %span.in-grey-600
            = t('.created_at')
        %td
          %span.in-grey-900.font-16.fw-300
            = order.creation_date
      %tr
        %td
          %span.in-grey-600
            = t('.status')
        %td
          %span.font-16.fw-300{ class: presenter.add_class_for_status(order) }
            = order.status
      %tr
        %td
          %span.in-grey-600
            = t('.total')
        %td
          %strong.font-16
            = number_to_currency(order.order_total)